COIN_KEYWORDS = {
    "BTC": ["bitcoin", "btc"],
    "ETH": ["ethereum", "eth", "ether"],
    "BNB": ["bnb", "binance coin"],
    "SOL": ["solana", "sol"],
    "XRP": ["ripple", "xrp"],
    "RENDER": ["Render", "render"],
    "WLD": ["Worldcoin", "wld"],
    "ADA": ["cardano", "ada"],
    "AVAX": ["avalanche", "avax"],
    "HYPE": ["Hyperliquid", "hype"],
    "DOT": ["polkadot", "dot"],
    "TON": ["Toncoin", "ton"],
    "TRX": ["tron", "trx"],
    "MATIC": ["polygon", "matic"],
    "NEAR": ["near protocol", "near"],
    "ATOM": ["cosmos", "atom"],
    "FTM": ["fantom", "ftm"],
    "ONDO": ["ondo"],
    "DOGE": ["dogecoin", "doge"],
    "SUI": ["Sui", "sui"],
    "SHIB": ["shiba inu", "shib"],
    "PEPE": ["pepe"],
    "BOME": ["bome"],
    "WIF": ["dogwifhat", "wif"],
    "FLOKI": ["floki"],
    "BONK": ["bonk"],
    "UNI": ["uniswap", "uni"],
    "LINK": ["chainlink", "link"],
    "AAVE": ["aave"],
    "LDO": ["lido", "ldo"],
    "MKR": ["maker", "mkr"],
    "CRV": ["curve dao", "crv"],
    "SUSHI": ["sushiswap", "sushi"],
    "DYDX": ["dydx"],
    "BITGET": ["bitget", "bgb"],
    "OP": ["optimism", "op"],
    "ARB": ["arbitrum", "arb"],
    "IMX": ["immutable x", "imx"],
    "QNT": ["Quant", "qnt"],
    "MANA": ["decentraland", "mana"],
    "AXS": ["axie infinity", "axs"],
    "GALA": ["gala"],
    "LTC": ["litecoin", "ltc"],
    "BCH": ["bitcoin cash", "bch"],
    "XLM": ["stellar", "xlm"],
    "XMR": ["monero", "xmr"],
    "ETC": ["ethereum classic", "etc"],
    "FIL": ["filecoin", "fil"],
    "ICP": ["internet computer", "icp"],
    "VET": ["vechain", "vet"],
    "HBAR": ["hedera", "hbar"]
}
